# config.yaml - UTF-8 Encoding
data_paths:
  largest_raw: "data/raw/LargeST"
  noaa_raw: "data/raw/NOAA" 
  twitter_raw: "data/raw/twitter"
  processed: "data/processed"
  fused: "data/fused"

time_settings:
  start_date: "2019-01-01"
  end_date: "2019-01-07"
  time_zone: "UTC"

largest:
  target_cities: ["california"]
  time_granularity: "5min"
  features: ["flow", "speed", "occupancy"]

noaa:
  features: ["temperature", "precipitation", "wind_speed", "humidity"]
  station_radius_km: 10

twitter:
  event_keywords: ["concert", "marathon", "festival", "accident", "protest"]
  min_retweets: 10

# 添加启用/禁用开关
enabled_modules:
  traffic: true
  weather: false  # 暂时禁用
  twitter: false  # 暂时禁用

model:
  seq_len: 12
  pred_len: 3
  batch_size: 32
  epochs: 100
  features: ["flow", "hour", "day_of_week", "is_weekend", "latitude", "longitude"]